version: "3.9"
services:
  kevstemplates:
    image: jekyll/jekyll:4.2.2
    restart: always
    volumes:
      - '/Users/kev/Web/kevstemplates.com:/srv/jekyll'
    ports:
      - "5555:5555"
      - "35729:35729"
    command: bash -c "gem install webrick && jekyll serve --host 0.0.0.0 --port 5555 --watch --force_polling --livereload --incremental"
    
# version: '3'
# services:
#   jekyll-serve:
#     image: jekyll/jekyll:4.0
#     volumes:
#       - '/Users/kev/Web/kevstemplates.com:/srv/jekyll'
#     ports:
#       - 5555:5555
#       - 35729:35729
#     command: "jekyll serve --watch --livereload"
